FROM node:19-alpine AS build

WORKDIR /front-react

# Copy only package files and the locally downloaded node_modules folder
COPY package*.json ./
# COPY node_modules/ ./node_modules/
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . .

EXPOSE 3000

CMD ["npm", "start"]