FROM node:19-alpine as build

WORKDIR /front-react

# Copy only package files and the locally downloaded node_modules folder
COPY package*.json ./
# COPY node_modules/ ./node_modules/
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
# RUN npm run build

# FROM nginx:alpine3.19

# Add the nginx configuration
# ADD nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built app from the build stage
# COPY --from=build /front-react/build /usr/share/nginx/html

EXPOSE 3000

CMD ["npm", "start"]

# CMD ["nginx", "-g", "daemon off;"]